language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chrissanders/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chrissanders/docker-react npm run test

